package com.shuyshuys.appwarung;

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author shuyshuys
 */

public class MasterBarang extends javax.swing.JFrame {

    public void getTable() {
        DefaultTableModel dataModel = new DefaultTableModel();
        dataModel.addColumn("ID");
        dataModel.addColumn("Nama");
        dataModel.addColumn("Harga");
        dataModel.addColumn("Kategori");

        try {
            String sql = "SELECT * FROM barang ORDER BY id_barang ASC";
            Statement statement = Post.getCon().createStatement();
            ResultSet rs = statement.executeQuery(sql);

            while (rs.next()) {
                dataModel.addRow(new Object[] { rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4) });
                jTabelLihat.setModel(dataModel);
                jTabelTambah.setModel(dataModel);
                jTabelUbah.setModel(dataModel);
                jTabelHapus.setModel(dataModel);
            }
            statement.close();
            rs.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Update Tabel Gagal!", "", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Creates new form MasterBarang
     */
    public MasterBarang() {
        initComponents();
        getTable();
    }

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int locX = ((screenSize.width - 720) / 2);
    int locY = ((screenSize.height - 640) / 2);
    // setLocation(new java.awt.Point(one, two));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTambah = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelTambah = new javax.swing.JTable();
        jLabelIdTambah = new javax.swing.JLabel();
        jTextFieldIdTambah = new javax.swing.JTextField();
        jLabelNamaTambah = new javax.swing.JLabel();
        jTextFieldNamaTambah = new javax.swing.JTextField();
        jLabelHargaTambah = new javax.swing.JLabel();
        jTextFieldHargaTambah = new javax.swing.JTextField();
        jLabelKategoriTambah = new javax.swing.JLabel();
        jTextFieldKategoriTambah = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jPanelUbah = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelUbah = new javax.swing.JTable();
        jButtonUbah = new javax.swing.JButton();
        jLabelIdUbah = new javax.swing.JLabel();
        jTextFieldIdUbah = new javax.swing.JTextField();
        jLabelNamaUbah = new javax.swing.JLabel();
        jTextFieldNamaUbah = new javax.swing.JTextField();
        jLabelHargaUbah = new javax.swing.JLabel();
        jTextFieldHargaUbah = new javax.swing.JTextField();
        jLabelKategoriUbah = new javax.swing.JLabel();
        jTextFieldKategoriUbah = new javax.swing.JTextField();
        jPanelHapus = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabelHapus = new javax.swing.JTable();
        jButtonHapus = new javax.swing.JButton();
        jLabelIdHapus = new javax.swing.JLabel();
        jTextFieldIdHapus = new javax.swing.JTextField();
        jLabelNamaHapus = new javax.swing.JLabel();
        jTextFieldNamaHapus = new javax.swing.JTextField();
        jLabelHargaHapus = new javax.swing.JLabel();
        jTextFieldHargaHapus = new javax.swing.JTextField();
        jLabelKategoriHapus = new javax.swing.JLabel();
        jTextFieldKategoriHapus = new javax.swing.JTextField();
        jPanelLihat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelLihat = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(locX, locY);
        setSize(new java.awt.Dimension(0, 0));

        jTabelTambah.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "ID Barang", "Nama", "Harga", "Kategori"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTabelTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelTambahMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTabelTambah);

        jLabelIdTambah.setText("ID");

        jLabelNamaTambah.setText("Nama");

        jLabelHargaTambah.setText("Harga");

        jLabelKategoriTambah.setText("Kategori");

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTambahLayout = new javax.swing.GroupLayout(jPanelTambah);
        jPanelTambah.setLayout(jPanelTambahLayout);
        jPanelTambahLayout.setHorizontalGroup(
                jPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTambahLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanelTambahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelKategoriTambah)
                                        .addComponent(jLabelNamaTambah)
                                        .addComponent(jLabelHargaTambah)
                                        .addComponent(jLabelIdTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanelTambahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNamaTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 150,
                                                Short.MAX_VALUE)
                                        .addComponent(jTextFieldHargaTambah)
                                        .addComponent(jTextFieldKategoriTambah)
                                        .addComponent(jTextFieldIdTambah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonTambah)
                                .addGap(18, 18, 18))
                        .addGroup(jPanelTambahLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanelTambahLayout.setVerticalGroup(
                jPanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTambahLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelTambahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldIdTambah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelIdTambah)
                                        .addComponent(jButtonTambah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTambahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNamaTambah)
                                        .addComponent(jTextFieldNamaTambah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTambahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldHargaTambah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelHargaTambah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTambahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelKategoriTambah)
                                        .addComponent(jTextFieldKategoriTambah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(91, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Tambah", jPanelTambah);

        jTabelUbah.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "ID Barang", "Nama", "Harga", "Kategori"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTabelUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelUbahMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTabelUbah);

        jButtonUbah.setText("Ubah");
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        jLabelIdUbah.setText("ID");

        jLabelNamaUbah.setText("Nama");

        jLabelHargaUbah.setText("Harga");

        jLabelKategoriUbah.setText("Kategori");

        javax.swing.GroupLayout jPanelUbahLayout = new javax.swing.GroupLayout(jPanelUbah);
        jPanelUbah.setLayout(jPanelUbahLayout);
        jPanelUbahLayout.setHorizontalGroup(
                jPanelUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelUbahLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(
                                        jPanelUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelKategoriUbah)
                                                .addComponent(jLabelNamaUbah)
                                                .addComponent(jLabelHargaUbah)
                                                .addComponent(jLabelIdUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanelUbahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldIdUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 150,
                                                Short.MAX_VALUE)
                                        .addComponent(jTextFieldNamaUbah)
                                        .addComponent(jTextFieldHargaUbah)
                                        .addComponent(jTextFieldKategoriUbah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonUbah)
                                .addGap(18, 18, 18))
                        .addGroup(jPanelUbahLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanelUbahLayout.setVerticalGroup(
                jPanelUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelUbahLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(
                                        jPanelUbahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldIdUbah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelIdUbah)
                                                .addComponent(jButtonUbah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelUbahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNamaUbah)
                                        .addComponent(jTextFieldNamaUbah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelUbahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldHargaUbah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelHargaUbah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelUbahLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelKategoriUbah)
                                        .addComponent(jTextFieldKategoriUbah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(91, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Ubah", jPanelUbah);

        jTabelHapus.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "ID Barang", "Nama", "Harga", "Kategori"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTabelHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelHapusMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTabelHapus);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jLabelIdHapus.setText("ID");

        jLabelNamaHapus.setText("Nama");

        jLabelHargaHapus.setText("Harga");

        jLabelKategoriHapus.setText("Kategori");

        javax.swing.GroupLayout jPanelHapusLayout = new javax.swing.GroupLayout(jPanelHapus);
        jPanelHapus.setLayout(jPanelHapusLayout);
        jPanelHapusLayout.setHorizontalGroup(
                jPanelHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHapusLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(
                                        jPanelHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelKategoriHapus)
                                                .addComponent(jLabelNamaHapus)
                                                .addComponent(jLabelHargaHapus)
                                                .addComponent(jLabelIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanelHapusLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldIdHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 150,
                                                Short.MAX_VALUE)
                                        .addComponent(jTextFieldNamaHapus)
                                        .addComponent(jTextFieldHargaHapus)
                                        .addComponent(jTextFieldKategoriHapus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385,
                                        Short.MAX_VALUE)
                                .addComponent(jButtonHapus)
                                .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHapusLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane4)
                                .addContainerGap()));
        jPanelHapusLayout.setVerticalGroup(
                jPanelHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHapusLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelHapusLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelIdHapus)
                                        .addComponent(jButtonHapus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHapusLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNamaHapus)
                                        .addComponent(jTextFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHapusLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldHargaHapus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelHargaHapus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHapusLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelKategoriHapus)
                                        .addComponent(jTextFieldKategoriHapus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(91, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Hapus", jPanelHapus);

        jTabelLihat.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "ID Barang", "Nama", "Harga", "Kategori"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabelLihat);

        javax.swing.GroupLayout jPanelLihatLayout = new javax.swing.GroupLayout(jPanelLihat);
        jPanelLihat.setLayout(jPanelLihatLayout);
        jPanelLihatLayout.setHorizontalGroup(
                jPanelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLihatLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanelLihatLayout.setVerticalGroup(
                jPanelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE));

        jTabbedPane1.addTab("Lihat", jPanelLihat);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 642, Short.MAX_VALUE)
                                .addComponent(jButtonBack)
                                .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonBack)
                                .addContainerGap(570, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelUbahMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTabelUbahMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTabelUbah.getModel();
        int selectedRowIndex = jTabelUbah.getSelectedRow();
        jTextFieldIdUbah.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextFieldNamaUbah.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jTextFieldHargaUbah.setText(model.getValueAt(selectedRowIndex, 2).toString());
        // jTextFieldStokHapus.setText(model.getValueAt(selectedRowIndex,
        // 3).toString());
        jTextFieldKategoriUbah.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }// GEN-LAST:event_jTabelUbahMouseClicked

    private void jTabelTambahMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTabelTambahMouseClicked

        // DefaultTableModel model = (DefaultTableModel) jTabelTambah.getModel();
        // int selectedRowIndex = jTabelTambah.getSelectedRow();
        // jTextFieldIdTambah.setText(model.getValueAt(selectedRowIndex, 0).toString());
        // jTextFieldNamaTambah.setText(model.getValueAt(selectedRowIndex,
        // 1).toString());
        // jTextFieldHargaTambah.setText(model.getValueAt(selectedRowIndex,
        // 2).toString());
        // // jTextFieldStokHapus.setText(model.getValueAt(selectedRowIndex,
        // // 3).toString());
        // jTextFieldKategoriTambah.setText(model.getValueAt(selectedRowIndex,
        // 3).toString());
    }// GEN-LAST:event_jTabelTambahMouseClicked

    // private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//
    // GEN-FIRST:event_jButtonUbahActionPerformed
    // // TODO add your handling code here:
    // }// GEN-LAST:event_jButtonUbahActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonBackActionPerformed
        // add your handling code here:
        dispose();
        // MasterMenu menu = new MasterMenu();
        MasterMenu.launchApp();
    }// GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonTambahActionPerformed
        // add your handling code here:
        String nama = jTextFieldNamaTambah.getText();
        String harga = jTextFieldHargaTambah.getText();
        // String stok = jTextFieldStokTambah.getText();
        String kategori = jTextFieldKategoriTambah.getText();
        // String keterangan = jTextFieldKeteranganTambah.getText();

        try {
            String sql = "";
            if (kategori.equalsIgnoreCase("makanan")) {
                sql = "INSERT INTO barang (id_barang, nama_barang, harga_barang, category_barang) VALUES (nextval('makanan'), '"
                        + nama + "', '" + harga + "', 'makanan');";
            } else if (kategori.equalsIgnoreCase("minuman")) {
                sql = "INSERT INTO barang (id_barang, nama_barang, harga_barang, category_barang) VALUES (nextval('minuman_sec'), '"
                        + nama + "', '" + harga + "', 'minuman');";
            }
            Statement stmt = Post.getCon().createStatement();
            stmt.executeUpdate(sql);
            stmt.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan!", "INPUT DATA",
                    JOptionPane.INFORMATION_MESSAGE);
            jTextFieldIdTambah.setText("");
            jTextFieldNamaTambah.setText("");
            jTextFieldHargaTambah.setText("");
            // jTextFieldStokTambah.setText("");
            jTextFieldKategoriTambah.setText("");
            // jTextFieldKeteranganTambah.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MasterBarang.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println(ex.getMessage());
        }
        getTable();
    }// GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonUbahActionPerformed
        // add your handling code here:
        String id = jTextFieldIdUbah.getText();
        String nama = jTextFieldNamaUbah.getText();
        String harga = jTextFieldHargaUbah.getText();
        // String stok = jTextFieldStokUbah.getText();
        String kategori = jTextFieldKategoriUbah.getText();
        // String detail = jTextFieldKeteranganUbah.getText();
        try {
            String sql = "UPDATE barang SET nama_barang = '" + nama + "', harga_barang = '" + harga
                    + "', category_barang = '" + kategori + "' WHERE barang.id_barang = '" + id + "'";
            Statement stmt = Post.getCon().createStatement();
            stmt.executeUpdate(sql);
            stmt.close();

            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah", "",
                    JOptionPane.INFORMATION_MESSAGE);
            jTextFieldIdUbah.setText("");
            jTextFieldNamaUbah.setText("");
            jTextFieldHargaUbah.setText("");
            // jTextFieldStokUbah.setText("");
            jTextFieldKategoriUbah.setText("");
            // jTextFieldKeteranganUbah.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MasterBarang.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println(ex.getMessage());
        }
        getTable();
    }// GEN-LAST:event_jButtonUbahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonHapusActionPerformed
        // add your handling code here:
        String id = jTextFieldIdHapus.getText();
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Apakah anda yakin ingin menghapus data ini?",
                    "Warning", dialogButton, JOptionPane.WARNING_MESSAGE);
            if (dialogResult == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM barang WHERE barang.id_barang = '" + id + " '";
                try {
                    Statement st = Post.getCon().createStatement();
                    st.executeUpdate(sql);
                    st.close();
                    // koneksi.getCon().createStatement().executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus", "",
                            JOptionPane.INFORMATION_MESSAGE);
                    getTable();
                    jTextFieldIdHapus.setText("");
                    jTextFieldNamaHapus.setText("");
                    jTextFieldHargaHapus.setText("");
                    jTextFieldKategoriHapus.setText("");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "",
                            JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(MasterBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_jButtonHapusActionPerformed

    private void jTabelHapusMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTabelHapusMouseClicked
        // add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTabelHapus.getModel();
        int selectedRowIndex = jTabelHapus.getSelectedRow();
        jTextFieldIdHapus.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextFieldNamaHapus.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jTextFieldHargaHapus.setText(model.getValueAt(selectedRowIndex, 2).toString());
        // jTextFieldStokHapus.setText(model.getValueAt(selectedRowIndex,
        // 3).toString());
        jTextFieldKategoriHapus.setText(model.getValueAt(selectedRowIndex, 3).toString());
        // jTextFieldKeteranganHapus.setText(model.getValueAt(selectedRowIndex,
        // 5).toString());
    }// GEN-LAST:event_jTabelHapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterBarang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JLabel jLabelHargaHapus;
    private javax.swing.JLabel jLabelHargaTambah;
    private javax.swing.JLabel jLabelHargaUbah;
    private javax.swing.JLabel jLabelIdHapus;
    private javax.swing.JLabel jLabelIdTambah;
    private javax.swing.JLabel jLabelIdUbah;
    private javax.swing.JLabel jLabelKategoriHapus;
    private javax.swing.JLabel jLabelKategoriTambah;
    private javax.swing.JLabel jLabelKategoriUbah;
    private javax.swing.JLabel jLabelNamaHapus;
    private javax.swing.JLabel jLabelNamaTambah;
    private javax.swing.JLabel jLabelNamaUbah;
    private javax.swing.JPanel jPanelHapus;
    private javax.swing.JPanel jPanelLihat;
    private javax.swing.JPanel jPanelTambah;
    private javax.swing.JPanel jPanelUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTabelHapus;
    private javax.swing.JTable jTabelLihat;
    private javax.swing.JTable jTabelTambah;
    private javax.swing.JTable jTabelUbah;
    private javax.swing.JTextField jTextFieldHargaHapus;
    private javax.swing.JTextField jTextFieldHargaTambah;
    private javax.swing.JTextField jTextFieldHargaUbah;
    private javax.swing.JTextField jTextFieldIdHapus;
    private javax.swing.JTextField jTextFieldIdTambah;
    private javax.swing.JTextField jTextFieldIdUbah;
    private javax.swing.JTextField jTextFieldKategoriHapus;
    private javax.swing.JTextField jTextFieldKategoriTambah;
    private javax.swing.JTextField jTextFieldKategoriUbah;
    private javax.swing.JTextField jTextFieldNamaHapus;
    private javax.swing.JTextField jTextFieldNamaTambah;
    private javax.swing.JTextField jTextFieldNamaUbah;
    // End of variables declaration//GEN-END:variables
}
